### ISSUE TITLE
::connect() error

### ISSUE THREAD

**Issue by ttocsr** [taganaka/SpeedTest#1]
Randomly when running a speedtest I'll get ::connect() error, this occurs with download and upload.  It also isn't every time.

SpeedTest++ version 1.5
Speedtest.net command line interface
Info: https://github.com/taganaka/SpeedTest
Author: Francesco Laurita francesco.laurita@gmail.com

IP: 104.157.82.47 ( TELUS ) Location: [53.5366, -113.51]
Finding fastest server... 4796 Servers online
............
Server: Edmonton, AB by Telus (1.342 km from you): 2 ms
Ping: 2 ms.
Jitter: 0 ms.
Finding fastest server for packet loss measurement... 81 Ping hosts online
.......
Server: Calgary by Platinum Communications (275.559 km from you):
Packets loss: 250
Determine line type (2) ........................
Fiber / Lan line type detected: profile selected fiber

Testing download speed (32) ................................................................................................................................................................
Download: 383.365 Mbit/s
Testing upload speed (16) ..........................................................................................................................................................................................................................::connect() error

**Comment by taganaka** [comment]
Hard to say what is not working here.

In the latest version I added a call to `perror` so that the reported error string should include more information about what went wrong during the socket connection.

Let me know if you can get more details about the error with this release

**Comment by ttocsr** [comment]
SpeedTest++ version 1.7
Speedtest.net command line interface
Info: https://github.com/taganaka/SpeedTest
Author: Francesco Laurita <francesco.laurita@gmail.com>

IP: 104.157.82.82 ( TELUS ) Location: [53.5366, -113.51]
Finding fastest server... 4841 Servers online
............
Server: Edmonton, AB by Telus (1.342 km from you): 2 ms
Ping: 2 ms.
Jitter: 0 ms.
Finding fastest server for packet loss measurement... 80 Ping hosts online
.......
Server: Lynnwood, WA by NetRiver (885.86 km from you):
Packets loss: 0
Determine line type (2) ........................
Fiber / Lan line type detected: profile selected fiber

Testing download speed (32) ................................................................................................................................
Download: 268.63 Mbit/s
Testing upload speed (16) ............................................................................................................................................................................................::connect() error: Connection timed out

**Comment by ttocsr** [comment]
Are there Ookla server version dependencies for reliably using TCP sockets?

**Comment by taganaka** [comment]
I can reproduce the error. The protocol looks the same but the server is definitively bugged.

After requesting a large amount of data during a download test, the server suddenly  drops the connection and the last chunk of data is garbage. I think this version has a pretty severe memory corruption bug. Going to release a fix to skip servers with version <=  2.3

**Comment by taganaka** [comment]
@ttocsr Would you mind to give a try to this branch?

https://github.com/taganaka/SpeedTest/tree/skip-obsolete-version

**Comment by ttocsr** [comment]
I tried this branch.  I thought we had success here, but after about the 4th run I'm getting the connect error.  I checked and the server that I connect to is ....
Connected to spd01.ar.ed.shawcable.net.
Escape character is '^]'.
HI
HELLO 2.3 2015-04-24.0629.291745c

.......here is the run that times out on this branch.

SpeedTest++ version 1.7
Speedtest.net command line interface
Info: https://github.com/taganaka/SpeedTest
Author: Francesco Laurita <francesco.laurita@gmail.com>

IP: 104.157.82.82 ( TELUS ) Location: [53.5366, -113.51]
Finding fastest server... 4851 Servers online
............
Server: Edmonton, AB by Shaw Communications (1.342 km from you): 3 ms
Ping: 3 ms.
Jitter: 0 ms.
Finding fastest server for packet loss measurement... 82 Ping hosts online
.......
Server: San Francisco, CA by Unwired (1909.88 km from you):
Packets loss: 0
Determine line type (2) ........................
Fiber / Lan line type detected: profile selected fiber

Testing download speed (32) ................................................................................................................................
Download: 269.74 Mbit/s
Testing upload speed (16) .............................................................................................................................................................................................::connect() error: Connection timed out

**Comment by taganaka** [comment]
Ok! You have a pretty badass connection! The template selected is maybe too aggressive and the target server refuses to ingest such a big upload payload.

Try again, with the latest commit. Thanks

**Comment by ttocsr** [comment]
I went to try it, but I think there is a new issue now.  I opened a new git issue.

**Comment by ttocsr** [comment]
It still times out with the new settings in this branch, but I see what to change now and where.  I used less threads and changed the time out and it runs, but I went to an extreme.  I'm going to slowly dial it back up and I'll post the settings that worked.  I'll also try it on a real badass connection...gige.
I see that they have a gigabit client template listed as well as a fiber template
http://www.ookla.com/support/a23000438/NetGauge-Client-Configuration-Templates

**Comment by taganaka** [comment]
Ok! Thanks. Let me know if you can find a better settings for high end speed connection.

I'll review ookla configuration template as well

**Comment by bobobox** [comment]
I'm also seeing 'Connection timed out' messages when running this, also with a fast (Gigabit fiber) connection:

`$ SpeedTest   
SpeedTest++ version 1.11  
Speedtest.net command line interface  
Info: https://github.com/taganaka/SpeedTest  
Author: Francesco Laurita <francesco.laurita@gmail.com>  
  
IP: 206.55.xxx.xxx ( US Internet Corp ) Location: [4x.xxxx, -9x.xxxx]  
Finding fastest server... 5497 Servers online  
............  
Server: Minnetonka, MN by US Internet (21.0995 km from you): 1 ms  
Ping: 1 ms.  
Jitter: 0 ms.  
Finding fastest server for packet loss measurement... 89 Ping hosts online  
.......  
Server: Chicago, IL by Ookla (556.191 km from you):   
Packets loss: 250  
Determine line type (2) ........................  
Fiber / Lan line type detected: profile selected fiber  
  
Testing download speed (32) ....................................................................................................................................................................................................::connect() error: Connection timed out  
*::connect() error: Connection timed out  
*::connect() error: Connection timed out  
*::connect() error: Connection timed out  
*  
Download: 547.41 Mbit/s  
Testing upload speed (12) ....................................................................................................................................................................................................................................
Upload: 322.30 Mbit/s
`
