### ISSUE TITLE
Dead host in list somewhere?

### ISSUE THREAD

**Issue by all-the-good-ones-are-gone** [taganaka/SpeedTest#11]
Whenever I run SpeedTest, I get the below as part of output, but I cannot locate any list in the files cloned:

> Finding fastest server... 7189 Servers online
> .......ERROR, no such host blf.speedtest.t-mobile.com
> *E.....

It then goes on to select a good host and continues.

**Comment by taganaka** [comment]
Hosts's list is loaded dynamically from here: http://c.speedtest.net/speedtest-servers-static.php
