### ISSUE TITLE
Question: How are the tests calculated?

### ISSUE THREAD

**Issue by HighMans** [taganaka/SpeedTest#12]
Hello! I'm trying out your program for the first time and I had a question regarding the results. If I do a test on speedtest.com it shows that I'm a tenth (or less) of what this program says my speed is. 

IP: XXX.XXX.XXX.XXX ( AT ) Location: [XX.XXX,XX.XXX]
Selected server: speedtest.uwyo.edu:8080
Ping: 55 ms.
Jitter: 0 ms.
Determine line type (2) ........................
Fiber / Lan line type detected: profile selected fiber

Testing download speed (32) ...................................................................................................................................................................................................
Download: 675.26 Mbit/s
Testing upload speed (12) ............................................................................................................................................................................................................................................................................................................................................................
Upload: 822.14 Mbit/s

However, running at speedtest.com gives me this:

![image](https://user-images.githubusercontent.com/1361790/44559905-f2d78900-a71a-11e8-8df2-5233004a5269.png)

Any insight would be appreciated! Thanks for your hardwork!

**Comment by HighMans** [comment]
I've figured out the issue, please close.

**Comment by taganaka** [comment]
Glad you've found a solution. I'm curious, what was the problem?

**Comment by HighMans** [comment]
It was purely a pebcak issue on my side. Sorry about the false-alarm.
