### ISSUE TITLE
Speedtests Much Higher Than Expected on Download Only

### ISSUE THREAD

**Issue by jbtt3615** [taganaka/SpeedTest#16]
We are currently testing this with a 250/250 connection. What we are seeing is accurate upload, but the download is almost always 300Mb/s and even as high as 530Mb/s. We are using a FTTH access platform and hard-coded to a max of 250/250. PC's etc. see 250Mb/s down.

Is there something I can do to make the download portion more accurate?

Thanks in advance!!

jb

**Comment by taganaka** [comment]
@jbtt3615 I may need more information as it hard to understand why you're seeing such of off results. 
Could you please let me know what's the architecture and SO used and maybe the server used during the test?

Thanks
