### ISSUE TITLE
Finding fastest server... Unable to initialize xml parser

### ISSUE THREAD

**Issue by ttocsr** [taganaka/SpeedTest#2]
CMakeLists.txt
change line 12 from set (SpeedTest_SERVER_LIST_URL "http://www.speedtest.net/speedtest-servers.php") 
to
set (SpeedTest_SERVER_LIST_URL "https://www.speedtest.net/speedtest-servers.php")

This resolved the issue for me.

**Comment by taganaka** [comment]
Thanks. On my end it works in either way.

I added your as default. Let's see if the secure url is more stable than the other

**Comment by zpeters** [comment]
Didn't check the code yet but are you sending a user agent string?  My github.com/zpeters/speedtest was blocked until i started sending one.

**Comment by ttocsr** [comment]
This is working now in version 1.7
