### ISSUE TITLE
Unable to download server list, all of February

### ISSUE THREAD

**Issue by all-the-good-ones-are-gone** [taganaka/SpeedTest#28]
Since the start of the month, I've had mail every cron job returning the bottom line:

```
$ SpeedTest
SpeedTest++ version 1.14
Speedtest.net command line interface
Info: https://github.com/taganaka/SpeedTest
Author: Francesco Laurita <francesco.laurita@gmail.com>

IP: <redacted> ( Verizon Fios ) Location: [<no>]
Finding fastest server... Unable to download server list. Try again later
```

Is there something wrong, or is my ISP now blocking traffic?

**Comment by Sagez** [comment]
I get same issue. it's not you.

**Comment by all-the-good-ones-are-gone** [comment]
This appears to have corrected on 2020-02-06, somewhere between 21:30 and 21:45 GMT.

**Comment by ansemjo** [comment]
FYI: my project `speedtest-plotter` hit the same issue [with any measurements scheduled for full or half hours](https://github.com/ansemjo/speedtest-plotter/issues/72#issuecomment-1054661494). It appears the endpoint simply returns `429` for a few seconds as the list is updated upstream. Just retry ~ 15 seconds later or add a little delay in your cron script.

**Comment by solsticedhiver** [comment]
As of 2022-11-22, I am having this problem, every time I try.
