### ISSUE TITLE
What license?

### ISSUE THREAD

**Issue by mkschreder** [taganaka/SpeedTest#3]
Just to be consistent, can you specify license? 

Can we agree on GPL?

**Comment by taganaka** [comment]
Hello @mkschreder 

Thanks for pointing this out.
I was thinking about something even more permissive like MIT 

I'm going to update the README file accordingly

**Comment by mkschreder** [comment]
Awesome. Thank you!

Here is my openwrt package and I have also made some minor changes to the
output to make it easy to parse by other cli utils..

https://github.com/mkschreder/juci-openwrt-feed/tree/master/speedtest-cpp
