### ISSUE TITLE
ability to specify server

### ISSUE THREAD

**Issue by ttocsr** [taganaka/SpeedTest#4]
It would be nice to be able to specify which server to run the test against.
I'm wondering if the issue i'm having with TCP sockets and this client is actually an issue with the server I always connect to being an older version.
telnet> open edmonton.speedtest.telus.com 8080
Trying 198.166.40.25...
Connected to edmonton.speedtest.telus.com.
Escape character is '^]'.
HI
HELLO 2.1 2013-08-14.01

**Comment by taganaka** [comment]
Good idea! Thanks
