### ISSUE TITLE
:connect() error: Connection refused

### ISSUE THREAD

**Issue by ttocsr** [taganaka/SpeedTest#5]
I tried with old version and new.
I'm wondering if there is a user agent string issue now like speedtest-cli had.
I tried from multiple connections and versions.  I tried speedtest-cli against the same servers and it runs, so my IP(s) aren't blocked.

SpeedTest++ version 1.7
Speedtest.net command line interface
Info: https://github.com/taganaka/SpeedTest
Author: Francesco Laurita francesco.laurita@gmail.com

IP: 104.157.82.47 ( TELUS ) Location: [53.5366, -113.51]
Finding fastest server... 4836 Servers online
....::connect() error: Connection refused

**Comment by ttocsr** [comment]
The user agent doesn't appear to be the issue.
I changed set (SpeedTest_API_KEY to a different value and I don't get connection refused.

**Comment by taganaka** [comment]
API_KEY is not related at all. It used just to generate a valid POST data signature when option --share is used. There should be a network hiccup somewhere else.

**Comment by taganaka** [comment]
Feel free to reopen the issue if the problem persists
