### ISSUE TITLE
SpeedTest++ 1.11 does not compile on gentoo

### ISSUE THREAD

**Issue by scardracs** [taganaka/SpeedTest#55]
Hi! I was trying to compile latest version of your program, but fails with the following error. For your convenience I'm gonna post the full build.log

[error.log](https://github.com/taganaka/SpeedTest/files/10061131/error.log)

**Comment by UnixRonin** [comment]
I find this report puzzling because I see only one Gentoo ebuild available, net-analyzer/speedtest++-0.0.20210829, and the SpeedTest binary installed by that ebuild reports its version as 1.14.  (And incidentally, it builds and runs fine with no problems.)

Are you using an overlay?

**Comment by scardracs** [comment]
Hi, I provide to you the ebuild here (change .log with .ebuild). Also I'd want to tell I had tried it against gcc-12.2.1 and ninja-1.11.1

[speedtest++-1.11.log](https://github.com/taganaka/SpeedTest/files/10089234/speedtest%2B%2B-1.11.log)
