### ISSUE TITLE
Needs to ignore some signals in case of connection error occurred

### ISSUE THREAD

**Issue by tt33415366** [taganaka/SpeedTest#6]
At least signal SIGPIPE is definitely should be ignored.
For those who suffers from connection error, and the program exit, just add
```c++
#include <csignal>
```
to your header file, and add
```c++
 signal(SIGPIPE, SIG_IGN);
```
to the very beginning of your main function(at least it should be called before any socket's connect/write function was called).

**Comment by taganaka** [comment]
It sounds good. 
Feel free to submit a PR

**Comment by taganaka** [comment]
Implemented here: https://github.com/taganaka/SpeedTest/commit/4ecabc88cc2e7426438b106cbda4438e3bf78dcc
