### ISSUE TITLE
Error: uncaught exception of stof

### ISSUE THREAD

**Issue by gglluukk** [taganaka/SpeedTest#60]
i've got similar errors using this handy tool at:
- openwrt:
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stof
Aborted
```

- macos:
```
libc++abi: terminating with uncaught exception of type std::invalid_argument: stof: no conversion
Abort trap: 6
```

**Comment by gglluukk** [comment]
patch is here: https://github.com/taganaka/SpeedTest/pull/61

**Comment by tcooper-xx** [comment]
Seems that whatever triggered this situation began to happen 3/20/24 between 11:31 and 11:46 GMT.

**Comment by napalmz** [comment]
I can confirm #61 fix it!
Pushed @gglluukk repo to my docker image and now works again.
I hope @taganaka will implement it...

**Comment by tb205gti** [comment]
Can confirm it solves the issue. Thanks

**Comment by gglluukk** [comment]
> The cause is this URL now seems to be throwing a 500 error: http://speedtest.ookla.com/api/ipaddress.php. Not exactly sure what it's behavior used to be, but potentially this could be replaced with a call to another API like this: https://ip-api.com/docs/api:json
> 
> Looks like it was getting the lat/lon & ISP name from that response.

I did some rewrites to replace http://speedtest.ookla.com/api/ipaddress.php with https://api.ipapi.is/ though I don't code in C++, so now it reports `IP: "1.2.3.4" (ISP)` with location
