### ISSUE TITLE
Strange speeds on Odroid-C2 (ARM)

### ISSUE THREAD

**Issue by ivan98** [taganaka/SpeedTest#7]
I am on a 1Gbps residential fiber link to a service provider who has an Ookla test server. On my Odroid-C2, which is a 64bit ARM, running Ubuntu 16.04, it gives impossible download values from 2,500Mbps to 3,500Mbps.

>$ uname -a
>Linux lhtest64 3.14.79-94 #1 SMP PREEMPT Mon Nov 21 17:13:27 BRST 2016 aarch64 aarch64 aarch64 GNU/Linux

>$ ./SpeedTest -t speedtest.xxxx.sg:8080 -p speedtest.xxxx.sg:8080 --output text
> IP=xx.xx.209.168
> IP_LAT=1.2855
> IP_LON=103.856
> PROVIDER=XXXX Fibre Broadband
> TEST_SERVER_HOST=speedtest.xxxx.sg:8080
> LATENCY=1
> JITTER=0
> QUALITY_SERVER_HOST=speedtest.xxxx.sg:8080
> PACKET_LOSS=120
> DOWNLOAD_SPEED=2551.67
> UPLOAD_SPEED=767.13

I've tried testing against another Ookla server in the same city (but different provider), and it still gives more than 1,000Mbps.

Very roughly speaking, the impossible values are about 4x what is expected.

I've recompiled with no effect. I've also tried iperf3 which gives 933 to 940Mbps, which is normal.

**Comment by ihang1** [comment]
Could it be c compiler issue? I tried on Mac OS, could give similar results as browser method.

**Comment by taganaka** [comment]
Thanks for reporting.
Do you have the chance to try it with the same server but on a different architecture?

**Comment by ihang1** [comment]
Hi, I did a tcp dump and notice using browser there is no "UDP, length 18" line, using the script I do see some UDP liner. Not sure is the cause of difference?

**Comment by taganaka** [comment]
Flash (used in the browser version) does not support UDP socket thus the "Line quality test" is not executed.

If you visit the page http://www.pingtest.net/ you can execute the "Line quality test" with UDP connection within your browser. It uses a java applet under the hood.

In short, UDP connection is mainly used to display 
```
PACKET_LOSS=xxx
```

**Comment by taganaka** [comment]
Waiting for some feedback on this: https://github.com/taganaka/SpeedTest/pull/18
